ARG NODE_VERSION
FROM node:${NODE_VERSION}

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY ./src ./src
COPY ./nest-cli.json ./
COPY ./tsconfig*.json ./
COPY --chown=node:node ./entrypoint-dev.sh ./

ENTRYPOINT [ "/bin/bash","/app/entrypoint-dev.sh" ]